# Generated by Django 3.0.5 on 2020-04-19 04:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=6, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('province', models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=100, verbose_name='Province')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
    ]
